FROM golang as gobuilder
COPY . /go/src/github.com/sapcc/containers/
RUN set -uex; \
    cd /go/src/github.com/sapcc/containers/backup-tools/backup-replication-image/go-src/; \
    export GOPATH=/go; \
    #go get ... ; \
    CGO_ENABLED=0 go build -v -ldflags '-s -w' -o /go/bin/replication-run; \
    mkdir -p /backup/env

FROM alpine
MAINTAINER "Josef Fröhle <josef.froehle@sap.com>, Norbert Tretkowski <norbert.tretkowski@sap.com>"
LABEL source_repository="https://github.com/sapcc/containers"

COPY --from=gobuilder /go/bin/replication-run /replication-run
COPY --from=gobuilder /backup/env /backup/env
RUN apk add --no-cache ca-certificates && update-ca-certificates
VOLUME ["/backup"]
ENTRYPOINT ["/replication-run"]
