FROM quay.io/coreos/etcd:v2.3.8

MAINTAINER "Josef Fröhle <josef.froehle@sap.com>, Norbert Tretkowski <norbert.tretkowski@sap.com>"

ADD files/busybox.tar.xz /
ADD files/backup-etcd.tar /bin/
ADD files/backup-certs.tar /

VOLUME ["/backup"]

ENTRYPOINT ["/bin/backup-etcd"]
